version: "3.9"

services:
  web:
    build: .
    container_name: videogamestore_web
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=VideoGameStoreDb;User=sa;Password=StrongPassword123!;TrustServerCertificate=True

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: videogamestore_db
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
